### ISSUE TITLE
Missing prettytime-parent 5.0.5 maven central

### ISSUE THREAD

**Issue by ahus1** [ocpsoft/prettytime#248]
My current build is missing the dependency on maven central: 

>  Failed to collect dependencies at org.ocpsoft.prettytime:prettytime:jar:5.0.5.Final: Failed to read artifact descriptor for org.ocpsoft.prettytime:prettytime:jar:5.0.5.Final: Could not find artifact org.ocpsoft.prettytime:prettytime-parent:pom:5.0.5.Final in central (https://repo.maven.apache.org/maven2) 

It seems to me that 5.0.4 is the latest published version: https://central.sonatype.dev/artifact/org.ocpsoft.prettytime/prettytime-parent/5.0.4.Final/versions

Could you please have a look?

**Comment by lincolnthree** [comment]
Looks like parent did not sync from sonatype from central despite it being updated and validated. I am working on a new release to try again. Thanks for reporting this.

**Comment by lincolnthree** [comment]
Re-released as 5.0.6.Final -- Hopefully this one syncs properly! Should be fixed as soon as Central updates.

**Comment by ahus1** [comment]
5.0.6.Final is now available, and I confirm that this works. I'll therefore close this issue. Thanks for fixing it.

The URL from Sonatype still shows a 500 error. As this is the new UI in development, and as they don't offer any contact to report this, I'll leave it at that.

**Comment by lincolnthree** [comment]
You're welcome, @ahus1, thanks so much again for reporting the issue! It's a strange one...
