### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by sgehrman** [ocpsoft/prettytime#68]
java.lang.ExceptionInInitializerError
at com.sickboots.sickvideos.b.run(Unknown Source)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.util.MissingResourceException: Can't find resource for bundle 'org.ocpsoft.prettytime.i18n.Resources_sv_SE', key ''
at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:237)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:229)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:160)
at a.b.a.b.b.b(Unknown Source)
at a.b.a.b.b.a(Unknown Source)
at a.b.a.c.a(Unknown Source)
at a.b.a.c.<init>(Unknown Source)
at com.sickboots.sickvideos.database.j.<clinit>(Unknown Source)
... 2 more

**Comment by levelibeeka** [comment]
Thanks @anubhavsahoo, it was a lifesaver!

**Comment by izBasit** [comment]
@lincolnthree Thanks for the library. It would be really great if your could just add
-keep class org.ocpsoft.prettytime.i18n.** under Proguard for android so that developers don't have to go digging for obfuscation. :)

**Comment by lincolnthree** [comment]
Hey @izBasit - it appears that ProGuard isn't for libraries, just apps. So there's nothing I can do here, unless you can show me what to do or send a pull request I'm afraid I'm unable to continue. Thanks!  Feel free to re-open if you find a solution I can implement.

**Comment by izBasit** [comment]
@lincolnthree Maybe I was unclear with my previous comment. Apologies for that.
In your ReadMe, can you please add the following message.
>
When using Proguard, please add
`-keep class org.ocpsoft.prettytime.i18n.**`
to your proguard script.

**Comment by lincolnthree** [comment]
Ah! I misunderstood. Thanks! I'll add that.

Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by peterdk** [comment]
We are using PrettyTime, but get errors while using Proguard. 
We use:  -keep class org.ocpsoft.prettytime.i18n.**
Error we get: 
java.util.MissingResourceException: Can't find resource for bundle 'org.ocpsoft.prettytime.i18n.Resources', key 'ePattern'
        at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
        at java.util.ResourceBundle.getObject(ResourceBundle.java:441)
        at java.util.ResourceBundle.getString(ResourceBundle.java:457)
        at org.ocpsoft.prettytime.i18n.Resources_ja$JaTimeFormat.<init>(SourceFile:155)
        at org.ocpsoft.prettytime.i18n.Resources_ja.getFormatFor(SourceFile:122)
        at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(SourceFile:34)
        at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(SourceFile:16)
        at org.ocpsoft.prettytime.PrettyTime.addUnit(SourceFile:714)
        at org.ocpsoft.prettytime.c.<init>(SourceFile:78)

Issue seems to be same as @ypresto 
I will investigate, but it seems to be useful to keep all classnames for the whole library, instead of the i18n package.
Something like: -keep class org.ocpsoft.prettytime.**

**Comment by peterdk** [comment]
I could reproduce the error, and with the following proguard config the error was gone. Please update the homepage.

```
-keep class org.ocpsoft.prettytime.** {*;}
-dontwarn org.ocpsoft.prettytime.**
```
This keeps all of the library, not only the i18n subpackage.

**Comment by shopmini** [comment]
The package name is changed.

I finally make it work with changing
`-keep class org.ocpsoft.prettytime.i18n.**`
to
`-keep class com.ocpsoft.pretty.time.i18n.** {*;}`

**Comment by asywalulfikri** [comment]
how to fix this 

 Failed resolution of: Lorg/ocpsoft/prettytime/PrettyTime;

**Comment by MahindraBhuman** [comment]
I am also facing the same issue....
Failed resolution of: Lorg/ocpsoft/prettytime/PrettyTime;
Class not found Exception...
I tried everything as per told here... 
But nothing comes out as useful ....

**Comment by masaibar** [comment]
In my case, I fixed like this.

```proguard-rules.pro
# for prettytime
-keep class com.ocpsoft.pretty.time.i18n.**
-keep class org.ocpsoft.prettytime.i18n.**
-keepnames class ** implements org.ocpsoft.prettytime.TimeUnit
```

**Comment by MML-Pro** [comment]
I still facing this issue even after add this lines on proguard file

`-keep class org.ocpsoft.prettytime.** {*;}
-dontwarn org.ocpsoft.prettytime.**
-keep class com.ocpsoft.pretty.time.i18n.** {*;}
-keep class org.ocpsoft.prettytime.i18n.Resources
-keepnames class ** implements org.ocpsoft.prettytime.TimeUnit`

**Comment by Piorko** [comment]
The problem does not arise for all languages, however, it occurs e.g. for the German language.
`-keep class com.ocpsoft.pretty.time.i18n.**
-keepnames class ** implements org.ocpsoft.prettytime.TimeUnit
`
this solves the problem.
